-- Kerala Play V3: rooms, players and live chat
create extension if not exists pgcrypto;

create table if not exists public.ludo_rooms (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  host_id uuid not null,
  status text not null default 'waiting',
  max_players int not null default 4 check (max_players between 2 and 4),
  game jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ludo_players (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.ludo_rooms(id) on delete cascade,
  user_id uuid not null,
  name text not null,
  color text not null,
  seat int not null check (seat between 0 and 3),
  joined_at timestamptz not null default now(),
  unique(room_id,user_id),
  unique(room_id,seat)
);

create table if not exists public.ludo_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.ludo_rooms(id) on delete cascade,
  user_id uuid not null,
  name text not null,
  text text not null check (char_length(text) between 1 and 300),
  created_at timestamptz not null default now()
);

alter table public.ludo_rooms enable row level security;
alter table public.ludo_players enable row level security;
alter table public.ludo_messages enable row level security;

drop policy if exists "rooms_auth_all" on public.ludo_rooms;
create policy "rooms_auth_all" on public.ludo_rooms for all to authenticated using (true) with check (true);

drop policy if exists "players_auth_all" on public.ludo_players;
create policy "players_auth_all" on public.ludo_players for all to authenticated using (true) with check (true);

drop policy if exists "messages_auth_all" on public.ludo_messages;
create policy "messages_auth_all" on public.ludo_messages for all to authenticated using (true) with check (true);

alter table public.ludo_rooms replica identity full;
alter table public.ludo_players replica identity full;
alter table public.ludo_messages replica identity full;

do $$ begin
  alter publication supabase_realtime add table public.ludo_rooms;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.ludo_players;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.ludo_messages;
exception when duplicate_object then null;
end $$;

-- Kerala Play account profiles. Authentication credentials remain in Supabase Auth;
-- this table stores only the public game identity used by the client.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 2 and 18),
  district text not null check (district in (
    'Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam',
    'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta',
    'Thiruvananthapuram', 'Thrissur', 'Wayanad'
  )),
  gender text not null default 'male' check (gender in ('male', 'female')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Upgrade older Kerala Play profile tables without deleting existing rows.
alter table public.profiles
  add column if not exists display_name text,
  add column if not exists district text,
  add column if not exists gender text default 'male',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

do $$
declare
  old_constraint record;
begin
  for old_constraint in
    select conname
    from pg_constraint
    where conrelid = 'public.profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%username%'
  loop
    execute format('alter table public.profiles drop constraint %I', old_constraint.conname);
  end loop;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'username'
  ) then
    execute 'alter table public.profiles alter column username drop not null';
    execute 'alter table public.profiles alter column username drop default';
  end if;
end $$;

alter table public.profiles enable row level security;

drop policy if exists "profiles_authenticated_read" on public.profiles;
create policy "profiles_authenticated_read"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_owner_insert" on public.profiles;
create policy "profiles_owner_insert"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_owner_update" on public.profiles;
create policy "profiles_owner_update"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create or replace function public.set_profile_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_profile_updated_at();

grant select, insert, update on public.profiles to authenticated;

-- Social graph: follows are public to signed-in players; blocks are private to
-- the blocker. Blocking removes follows in both directions.
create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create index if not exists follows_following_id_idx on public.follows(following_id);
create index if not exists blocks_blocked_id_idx on public.blocks(blocked_id);

alter table public.follows enable row level security;
alter table public.blocks enable row level security;

create or replace function public.users_are_blocked(user_a uuid, user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.blocks
    where (blocker_id = user_a and blocked_id = user_b)
       or (blocker_id = user_b and blocked_id = user_a)
  );
$$;

create or replace function public.can_view_profile(profile_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select profile_id = (select auth.uid())
    or exists (
      select 1 from public.blocks
      where blocker_id = (select auth.uid()) and blocked_id = profile_id
    )
    or not public.users_are_blocked((select auth.uid()), profile_id);
$$;

revoke all on function public.users_are_blocked(uuid, uuid) from public;
revoke all on function public.can_view_profile(uuid) from public;
grant execute on function public.users_are_blocked(uuid, uuid) to authenticated;
grant execute on function public.can_view_profile(uuid) to authenticated;

drop policy if exists "profiles_authenticated_read" on public.profiles;
create policy "profiles_authenticated_read"
on public.profiles for select
to authenticated
using (public.can_view_profile(id));

drop policy if exists "follows_authenticated_read" on public.follows;
create policy "follows_authenticated_read"
on public.follows for select
to authenticated
using (
  public.can_view_profile(follower_id)
  and public.can_view_profile(following_id)
);

drop policy if exists "follows_owner_insert" on public.follows;
create policy "follows_owner_insert"
on public.follows for insert
to authenticated
with check (
  follower_id = (select auth.uid())
  and following_id <> (select auth.uid())
  and not public.users_are_blocked(follower_id, following_id)
);

drop policy if exists "follows_owner_delete" on public.follows;
create policy "follows_owner_delete"
on public.follows for delete
to authenticated
using (follower_id = (select auth.uid()));

drop policy if exists "blocks_owner_read" on public.blocks;
create policy "blocks_owner_read"
on public.blocks for select
to authenticated
using (blocker_id = (select auth.uid()));

drop policy if exists "blocks_owner_insert" on public.blocks;
create policy "blocks_owner_insert"
on public.blocks for insert
to authenticated
with check (blocker_id = (select auth.uid()) and blocked_id <> (select auth.uid()));

drop policy if exists "blocks_owner_delete" on public.blocks;
create policy "blocks_owner_delete"
on public.blocks for delete
to authenticated
using (blocker_id = (select auth.uid()));

create or replace function public.cleanup_follows_after_block()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.follows
  where (follower_id = new.blocker_id and following_id = new.blocked_id)
     or (follower_id = new.blocked_id and following_id = new.blocker_id);
  return new;
end;
$$;

revoke all on function public.cleanup_follows_after_block() from public;

drop trigger if exists blocks_cleanup_follows on public.blocks;
create trigger blocks_cleanup_follows
after insert on public.blocks
for each row execute function public.cleanup_follows_after_block();

grant select, insert, delete on public.follows to authenticated;
grant select, insert, delete on public.blocks to authenticated;

notify pgrst, 'reload schema';
