-- Kerala Play V3: rooms, players and live chat
create extension if not exists pgcrypto;

create table if not exists public.ludo_rooms (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  host_id uuid not null,
  status text not null default 'waiting',
  max_players int not null default 4 check (max_players between 2 and 4),
  game jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ludo_players (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.ludo_rooms(id) on delete cascade,
  user_id uuid not null,
  name text not null,
  color text not null,
  seat int not null check (seat between 0 and 3),
  joined_at timestamptz not null default now(),
  unique(room_id,user_id),
  unique(room_id,seat)
);

create table if not exists public.ludo_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.ludo_rooms(id) on delete cascade,
  user_id uuid not null,
  name text not null,
  text text not null check (char_length(text) between 1 and 300),
  created_at timestamptz not null default now()
);

alter table public.ludo_rooms enable row level security;
alter table public.ludo_players enable row level security;
alter table public.ludo_messages enable row level security;

drop policy if exists "rooms_auth_all" on public.ludo_rooms;
create policy "rooms_auth_all" on public.ludo_rooms for all to authenticated using (true) with check (true);

drop policy if exists "players_auth_all" on public.ludo_players;
create policy "players_auth_all" on public.ludo_players for all to authenticated using (true) with check (true);

drop policy if exists "messages_auth_all" on public.ludo_messages;
create policy "messages_auth_all" on public.ludo_messages for all to authenticated using (true) with check (true);

alter table public.ludo_rooms replica identity full;
alter table public.ludo_players replica identity full;
alter table public.ludo_messages replica identity full;

do $$ begin
  alter publication supabase_realtime add table public.ludo_rooms;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.ludo_players;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.ludo_messages;
exception when duplicate_object then null;
end $$;

-- Kerala Play account profiles. Authentication credentials remain in Supabase Auth;
-- this table stores only the public game identity used by the client.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 2 and 18),
  district text not null check (district in (
    'Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam',
    'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta',
    'Thiruvananthapuram', 'Thrissur', 'Wayanad'
  )),
  gender text not null default 'male' check (gender in ('male', 'female')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_authenticated_read" on public.profiles;
create policy "profiles_authenticated_read"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles_owner_insert" on public.profiles;
create policy "profiles_owner_insert"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles_owner_update" on public.profiles;
create policy "profiles_owner_update"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create or replace function public.set_profile_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_profile_updated_at();

grant select, insert, update on public.profiles to authenticated;
